### ISSUE TITLE
featured image gets pushed down by text

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/8106-tv#100]
this is around 688x1115

![](http://puu.sh/opRIT/5c71692e54.png)

**Comment by varffs** [comment]
i thought there was supposed to be a limit to the text tho?

**Comment by mixcas** [comment]
yeah but this example title/subtitle is really not that long:

![](http://puu.sh/opS0F/4381a92afd.png)

**Comment by mixcas** [comment]
The image has a base width of `s14`. Making is s15 will also prove more vertical space for the text to fit overall better.

![](http://puu.sh/opRRQ/78684b5df1.png)

![](http://puu.sh/opRWj/7f585f8edf.png)

![](http://puu.sh/opRZ4/c5617b5b36.png)

**Comment by varffs** [comment]
but it makes the image too big. better to add the equivilant padding to the top of the image

**Comment by mixcas** [comment]
@varffs What do you mean? Add some padding top in order to give more veritcal space? sounds good

**Comment by varffs** [comment]
Yes that
