### ISSUE TITLE
menu items are too close in mobile

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/8106-tv#109]
![](https://scontent-dfw1-1.xx.fbcdn.net/hphotos-xap1/v/t34.0-12/13084267_10157017442360107_213255182_n.jpg?oh=1268c12bfe31d4f3a93ecc1a95ef7ce1&oe=571B8799)

how do we solve this @varffs ??
make the search smaller?

**Comment by varffs** [comment]
The code actually dont make any sense. Apparently there are all 100% width non floated?! Can we use Flex to lay them out according to their existing widths?
