### ISSUE TITLE
use requestAnimationFrame() instead of setInterval()

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/8106-tv#29]
https://github.com/interglobalvision/8106-tv/blob/master/js/main.js#L52

**Comment by varffs** [comment]
I considered using animation frame etc but I didn't really know how to do that and didn't think it was worth spending the time on tbh. Would there be significant perf improvements?

**Comment by mixcas** [comment]
I think it wont take more than 20 min and it would make a big diff.
Its not a priority tho.

ps. @varffs cmon! learn requestAnimationFrame ¬¬

**Comment by varffs** [comment]
this is a nice animation: http://jsfiddle.net/XQpzU/4358/?utm_source=website&utm_medium=embed&utm_campaign=XQpzU Probably useful ref code too
