### ISSUE TITLE
.copy p max-width

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/8106-tv#32]
Shouldn't this be dynamic?
https://github.com/interglobalvision/8106-tv/blob/master/css/site.styl#L132

like
`max-width: ( 14 * $col ) + ( ( 14 - 1 ) * $gutter )`

**Comment by varffs** [comment]
this is now. but just margins of 1 col on left and right:

`````` .copy
  p, h1, h2, h3, h4, h5, h6
    margin-left: $col + ($gutter * 1.5)
    margin-right: $col + ($gutter * 1.5)```
``````
